### ISSUE TITLE
How to run the omxplayer-pi snap on core18?

### ISSUE THREAD

**Issue by lorenzhaberzettl** [ogra1/omxplayer-snap#6]
Hey there!

First off, I have to say, I'm a little bit embarrassed to have to ask this, but how do I get the omxplayer-pi snap running on Ubuntu Core 18?

My steps are these:

1. modify /boot/uboot/config.txt (comment the dtoverlay directive)
2. reboot
3. install the omxplayer-pi snap
4. run omxplayer-pi video.webm

This, however, does not produce any video output. Because of https://github.com/ogra1/omxplayer-snap/issues/2 I also tried installing mir-kiosk, without luck.

Am I missing anything crucial?

**Comment by ogra1** [comment]
there was a bug in the compiler flags that somehow slipped through, it is now fixed in the edge channel, you can ```snap install omxplayer-pi --edge``` to test it ... note that the instructions in the package description also got updated, it is not necessary anymore to change the config.txt settings, the latest build should work fine with the dtoverlay enabled ... 

i tested on the universal Pi image downloaded from:
http://cdimage.ubuntu.com/ubuntu-core/18/stable/current/ubuntu-core-18-arm64+raspi.img.xz
written to SD, completed the setup for network and user and then using the following steps via ssh:
```
snap install omxplayer-pi --edge
snap connect omxplayer-pi:hardware-observe
snap connect omxplayer-pi:home
snap install mget
snap connect mget:home
mget https://download.blender.org/demo/movies/tears-of-steel_teaser.mp4
omxplayer-pi --loop tears-of-steel_teaser.mp4
```

this plays fine on a pi3 b+ and pi4 ...

**Comment by lorenzhaberzettl** [comment]
Thanks a lot. This is now working for me :smiley:
